### ISSUE TITLE
Nuxt Build Issue

### ISSUE THREAD

**Issue by circlebeats** [xLeDocteurx/p5wrappers#1]
`Cannot find module 'react' Require stack: - C:\Users\ben2\Documents\Circ\circ2023\node_modules\p5wrappers\dist\index.js - C:\Users\ben2\Documents\Circ\circ2023\node_modules\vue-server-renderer\build.dev.js - C:\Users\ben2\Documents\Circ\circ2023\node_modules\vue-server-renderer\index.js - C:\Users\ben2\Documents\Circ\circ2023\node_modules\@nuxt\vue-renderer\dist\vue-renderer.js - C:\Users\ben2\Documents\Circ\circ2023\node_modules\@nuxt\server\dist\server.js - C:\Users\ben2\Documents\Circ\circ2023\node_modules\@nuxt\core\dist\core.js - C:\Users\ben2\Documents\Circ\circ2023\node_modules\nuxt\dist\nuxt.js - C:\Users\ben2\Documents\Circ\circ2023\server\index.js`

I get this error when trying to run nuxt instance locally. Have tried running it in SSR and SPA modes with same results. I've also tried building for production then removing the problem files in the dist folder after the build with similar error.

**Comment by xLeDocteurx** [comment]
Sorry for the late responce mate ! ( My pregnant girlfriend had an accident, it was the two worst days of my life. Everything is fine now, i'm back to business )

The issue comes from the way I use the bundling tool.
I'm using Bili wich is based on Rollup and provide an abstraction layer wich makes things easier to build a package.

I'm still working on it. I will either way change Bili configuration or remove Bili and use rollup directly to prevent the bundler to require react in the index.js file.

This #$@£²# of Bili automaticaly place those too lines after compiling.
```javascript
var React = require('react');
var React__default = _interopDefault(React);
```
But only for react and not vue. Th easiest fix would be to remove those too line before publishing on npm each time. xD

Your issue also made me notice that the whole P5 library is packed with the package. ( making it 4.31 MB raw / 652Kb Gzipped )
It should be 5,5Kb raw / 1.79Kb Gzipped

Anyway i'm fixing this right now
